FROM scratch

ENV MICROSSY_LOCAL_HOST 0.0.0.0
ENV MICROSSY_LOCAL_PORT 8080
ENV MICROSSY_LOG_LEVEL 0

EXPOSE $MICROSSY_LOCAL_PORT

COPY certs /etc/ssl/
COPY bin/linux-amd64/microssy /

CMD ["/microssy"]
